import { CatalogSeedItem } from './catalog-seed-item.model';

export const CATALOG_SEED_DATA: CatalogSeedItem[] = [

  {
    id: 1,
    name: 'Masturbador Masculino Egg Wavy Magical Kiss',
    slug: 'masturbador-masculino-egg-wavy-magical-kiss',
    description: 'Presente dos deuses” que transforma a masturbação em pura perdição',
    longDescription: 'Cada ovo vem com uma textura diferente em sua embalagem, para transformar e proporciona sua experiência em uma grande aventura, seja ela a dois ou sozinha. Produto Unissex',
    imgUrl: 'egg-masturbador.webp',
    imageAlt: 'Masturbador Masculino Egg Wavy Magical Kiss',
    price: 25,
    compareAtPrice: 35,
    category: 'Masturbadores',
    tags: ['egg', 'masturbador', 'egg-wavy'],
    rating: 4.8,
    reviewCount: 52,
    highlights: ['pura perdição', 'ovinho de prazer', 'Masturbador Masculino'],
  },
  {
    id: 2,
    slug: 'lubrificante-d4-chiclete',
    name: 'Lubrificante D4 Chiclete 60g',
    description: 'Lubrificante íntimo beijável com sabor chiclete.',
    longDescription: 'Produto de base aquosa que proporciona lubrificação intensa, ideal para momentos mais confortáveis e prazerosos.',
    imgUrl: 'd4-chiclete.avif',
    imageAlt: 'Lubrificante íntimo sabor chiclete',
    price: 25,
    category: 'Lubrificantes',
    tags: ['lubrificante', 'chiclete', 'beijavel', 'd4'],
    rating: 4.7,
    reviewCount: 35,
    highlights: ['Base aquosa', 'Beijável', 'Alta lubrificação'],
  },
  {
    id: 3,
    slug: 'algema-metal-pelucia-preta-hand-cuffs',
    name: 'Algema de Metal com Pelúcia Preta HAND CUFFS',
    description: 'A Algema é o acessório perfeito para suas práticas de dominação e submissão.',
    longDescription: 'A algema conta com um material em metal que permite maior rigidez e segurança para a pessoa não se soltar. Já a pelúcia vem trazendo todo o charme e luxo para o item. Sendo um acessório que abre um leque de opções na hora H, dome seu amor e mostre quem está no controle da situação!',
    imgUrl: 'algemas-hand-cuffs.jpeg',
    imageAlt: 'Algema com pelúcia preta hand cuffs',
    price: 25,
    category: 'Acessórios',
    tags: ['algema', 'fantasia', 'acessorio'],
    rating: 4.6,
    reviewCount: 22,
    highlights: ['Conforto', 'Resistente', 'Estilo'],
  },
  {
    id: 4,
    slug: 'gel-termico-beijável-yummy',
    name: 'Gel Térmico Beijável Yummy vários sabores',
    description: 'O Yummy Gel Térmico Beijável é o segredo que vai transformar seus momentos de prazer em experiências inesquecíveis.',
    longDescription: 'Com uma variedade deliciosa de sabores, como morango, menta, e chiclete, este gel é perfeito para quem deseja adicionar um toque especial ao sexo oral, tornando cada momento ainda mais gostoso e divertido.',
    imgUrl: 'gel-termico.jpg',
    imageAlt: 'Gel térmico beijável com sabores variados',
    price: 15,
    category: 'Géis',
    tags: ['gel', 'beijavel', 'sabores', 'termico'],
    rating: 4.9,
    reviewCount: 64,
    highlights: ['Beijável', 'Sabores variados', 'Efeito térmico'],
  },
  {
    id: 5,
    slug: 'lubrificante-d4-morango',
    name: 'Lubrificante D4 Morango 60g',
    description: 'Lubrificante íntimo beijável com sabor morango e base aquosa.',
    longDescription: 'Fórmula leve, não gordurosa e solúvel em água. Proporciona maior conforto durante o uso e intensifica o prazer.',
    imgUrl: 'd4-morango.avif',
    imageAlt: 'Lubrificante íntimo sabor morango',
    price: 25,
    category: 'Lubrificantes',
    tags: ['lubrificante', 'morango', 'beijavel', 'd4'],
    rating: 4.8,
    reviewCount: 40,
    highlights: ['Base aquosa', 'Beijável', 'Conforto'],
  },
  {
    id: 6,
    slug: 'vibrador-golfinho-ponto-g',
    name: 'Vibrador Golfinho Ponto G',
    description: 'Vibrador com formato de golfinho para estimulação do ponto G.',
    longDescription: 'Design anatômico que proporciona prazer intenso e múltiplos orgasmos, ideal para uso individual.',
    imgUrl: 'vibrador-golfinho.jpg',
    imageAlt: 'Vibrador formato golfinho',
    price: 20,
    category: 'Vibradores',
    tags: ['vibrador', 'ponto-g', 'golfinho'],
    rating: 4.8,
    reviewCount: 70,
    highlights: ['Ponto G', 'Ergonômico', 'Best-seller'],

  },
  {
    id: 7,

    slug: 'tesao-de-touro',
    name: 'Tesão de Touro Afrodisíaco',
    description: 'O Tesão de Touro é o estimulante natural afrodisíaco que você estava procurando!',
    longDescription: 'Perfeito para homens que desejam aumentar o apetite sexual e transformar suas noites em momentos cheios de energia e disposição, este produto vai fazer você subir pelas paredes de tanto desejo. Prepare-se para explorar cada momento ao máximo!',
    imgUrl: 'tesao-de-touro.webp',
    imageAlt: 'Afrodisíaco masculino',
    price: 9.99,
    compareAtPrice: 14.99,
    category: 'Afrodisíacos',
    tags: ['afrodisiaco', 'masculino'],
    rating: 4.6,
    reviewCount: 28,
    highlights: ['Energia', 'Desempenho'],
  },
  {
    id: 8,
    slug: 'algema-metal-pelucia',
    name: 'Algema de Metal com Pelúcia',
    description: 'A Algema é o acessório perfeito para suas práticas de dominação e submissão.',
    longDescription: 'A algema conta com um material em metal que permite maior rigidez e segurança para a pessoa não se soltar. Já a pelúcia vem trazendo todo o charme e luxo para o item. Sendo um acessório que abre um leque de opções na hora H, dome seu amor e mostre quem está no controle da situação!',
    imgUrl: 'algemas-veludo.jpeg',
    imageAlt: 'Algema com pelúcia',
    price: 25,
    category: 'Acessórios',
    tags: ['algema', 'fantasia', 'acessorio'],
    rating: 4.6,
    reviewCount: 22,
    highlights: ['Conforto', 'Resistente', 'Estilo'],
  },
  {
    id: 9,
    slug: 'hot-ball-xana-loka',
    name: 'Hot Ball Xana Loka',
    description: 'Cápsulas excitantes com efeito térmico e vibratório para intensificar o prazer.',
    longDescription: 'As Hot Balls proporcionam uma explosão de sensações com efeitos de aquecimento, refrescância e vibração. Perfeitas para elevar as preliminares e criar experiências inesquecíveis.',
    imgUrl: 'xana-louca.jpg',
    imageAlt: 'Cápsulas excitantes com efeito térmico',
    price: 20,
    category: 'Acessórios',
    tags: ['capsula', 'vibracao', 'excitante', 'xana-loka'],
    rating: 4.7,
    reviewCount: 38,
    highlights: ['Dupla unidade', 'Efeito térmico', 'Preliminares'],
  },
  {
    id: 10,
    slug: 'gel-excitante-xana-loka-liquido-15g',
    name: 'Gel Excitante Xana Loka Líquido 15g',
    description: 'Gel excitante com efeito esquenta, esfria e vibra, proporcionando sensações intensas.',
    longDescription: 'Produto desenvolvido para aumentar o prazer, promovendo aquecimento, refrescância e vibração ao mesmo tempo. Ideal para explorar novas sensações e intensificar momentos íntimos.',
    imgUrl: 'xana-louca-hotflowers.jpeg',
    imageAlt: 'Gel excitante líquido com efeitos térmicos e vibratórios',
    price: 25,
    category: 'Géis',
    tags: ['gel', 'excitante', 'esquenta-esfria', 'vibracao', 'xana-loka'],
    rating: 4.8,
    reviewCount: 52,
    highlights: ['Esquenta e esfria', 'Vibração', 'Alta intensidade'],

  },
  {
    id: 11,
    slug: 'capsula-vibratoria-dupla',
    name: 'Cápsula Vibratória Estimuladora Bullet Dupla - VibraToy',
    description: 'Vibrador com dupla estimulação para máximo prazer.',
    longDescription: 'Possui uma cápsula para estimular o clitóris e outras para o ponto G, elevando ao máximo o seu prazer e com facilidade chegar ao orgasmo.',
    imgUrl: 'capsula-vibratoria.jpeg',
    imageAlt: 'Cápsula Vibratória Estimuladora Bullet Dupla - VibraToy',
    price: 35,
    compareAtPrice: 45,
    category: 'Vibradores',
    tags: ['vibrador', 'capsula', 'dupla-estimulacao'],
    rating: 4.9,
    reviewCount: 55,
    highlights: ['Dupla vibração', 'Alta intensidade'],
  },
  {
    id: 12,
    slug: 'capsula-vibratoria-bullet',
    name: 'Cápsula Vibratória Bullet',
    description: 'Vibrador compacto com múltiplas velocidades.',
    longDescription: 'Pequeno, discreto e potente, ideal para estimulação sensível. Indicado para o clitóris, pois essa região é ultra sensível, possuindo milhares de terminações nervosas. Perfeito para outras regiões erógenas (como nuca, pescoço, interior das coxas), especialmente nas preliminares, para apimentar o momento íntimo',
    imgUrl: 'capsula-vibratoria-bullet.jpeg',
    imageAlt: 'Cápsula vibratória pequena',
    price: 20,
    category: 'Vibradores',
    tags: ['vibrador', 'bullet', 'compacto'],
    rating: 4.7,
    reviewCount: 41,
    highlights: ['Compacto', 'Multivelocidades'],
  },
  {
    id: 13,
    slug: 'tesao-de-vaca',
    name: 'Tesão de Vaca Afrodisíaco',
    description: 'Estimulante natural feminino para aumentar o desejo.',
    longDescription: 'Afrodisíaco desenvolvido para intensificar a libido e proporcionar mais energia nos momentos íntimos.',
    imgUrl: 'tesao-de-vaca.jpeg',
    imageAlt: 'Afrodisíaco feminino',
    price: 9.99,
    category: 'Afrodisíacos',
    tags: ['afrodisiaco', 'feminino'],
    rating: 4.5,
    reviewCount: 30,
    highlights: ['Natural', 'Estimula libido'],
  },
  {
    id: 14,
    slug: 'lubrificante-d4-siliconado',
    name: 'Lubrificante D4 Siliconado 60g',
    description: 'Quem nunca teve vontade de transar na água, não é mesmo? Seja no chuveiro, na banheira, na piscina ou até na cachoeira ou no mar para os mais aventureiros. E que tal deixar tudo ainda mais fácil e prático? Com o D4 Lubrificante Íntimo Siliconado, seus dias e suas noites serão regados de emoção como nunca. Apenas o céu é o limite.',
    longDescription: 'Lubrificante siliconado é uma boa opção para os casais que nunca perdem o fôlego, por conta da sua durabilidade não precisa ser reaplicado toda hora e ainda é uma ótima alternativa para ser usada junto com preservativos.',
    imgUrl: 'd4.png',
    imageAlt: 'Lubrificante siliconado de longa duração',
    price: 30,
    compareAtPrice: 40,
    category: 'Lubrificantes',
    tags: ['lubrificante', 'siliconado', 'durabilidade', 'd4'],
    rating: 4.9,
    reviewCount: 48,
    highlights: ['Longa duração', 'Resistente à água', 'Premium'],
  },
  {
    id: 15,
    slug: 'capa-peniana-silicone',
    name: 'Capa Extensora Peniana em Silicone La Pimienta 16cm',
    description: 'A Capa Peniana Expansora é o acessório ideal para quem deseja aumentar a rigidez e o tamanho do pênis, proporcionando uma experiência intensa e estimulante.',
    longDescription: 'Fabricada com um material flexível e elástico, ela se adapta facilmente ao formato do pênis, garantindo conforto e facilidade de uso.',
    imgUrl: 'capa-extensora.webp',
    imageAlt: 'Extensor peniano de silicone',
    price: 30,
    category: 'Acessórios',
    tags: ['capa', 'extensor', 'silicone'],
    rating: 4.4,
    reviewCount: 18,
    highlights: ['Flexível', 'Confortável'],
  },
  {
    id: 16,
    slug: 'plug-com-pedra-de-metal-tamanho-p',
    name: 'Plug com Pedra de Metal Tamanho P',
    description: 'Acessório erótico ideal para os casais que não tenham medo de experimentar seus maiores fetiches,principalmente se contém jogos de dominação e submissão.',
    longDescription: 'Ele serve para que você possa se preparar para a penetração anal,dilatando o ânus, ou ainda para a estimulação anal,deixando o momento mais emocionantee, prologando o seu prazer e deixando a relação ainda mais gostosa e prazerosa.',
    imgUrl: 'plug-tamanhop.jpg',
    imageAlt: 'plug anal com pedra de metal',
    price: 35,
    category: 'Acessórios',
    tags: ['plug', 'anal', 'metal'],
    rating: 4.4,
    reviewCount: 18,
    highlights: ['Pedra de metal', 'Submissão', 'Estímulo anal'],
  },
  {
    id: 17,
    slug: 'plug-com-pedra-de-metal-tamanho-m',
    name: 'Plug com Pedra de Metal Tamanho M',
    description: 'Acessório erótico ideal para os casais que não tenham medo de experimentar seus maiores fetiches,principalmente se contém jogos de dominação e submissão.',
    longDescription: 'Ele serve para que você possa se preparar para a penetração anal,dilatando o ânus, ou ainda para a estimulação anal,deixando o momento mais emocionantee, prologando o seu prazer e deixando a relação ainda mais gostosa e prazerosa.',
    imgUrl: 'plug-pedra.jpeg',
    imageAlt: 'plug anal com pedra de metal',
    price: 45,
    category: 'Acessórios',
    tags: ['plug', 'anal', 'metal'],
    rating: 4.4,
    reviewCount: 18,
    highlights: ['Pedra de metal', 'Submissão', 'Estímulo anal'],
  },
  {
    id: 18,
    slug: 'plug-com-pedra-de-metal-tamanho-g',
    name: 'Plug com Pedra de Metal Tamanho G',
    description: 'Acessório erótico ideal para os casais que não tenham medo de experimentar seus maiores fetiches,principalmente se contém jogos de dominação e submissão.',
    longDescription: 'Ele serve para que você possa se preparar para a penetração anal,dilatando o ânus, ou ainda para a estimulação anal,deixando o momento mais emocionantee, prologando o seu prazer e deixando a relação ainda mais gostosa e prazerosa.',
    imgUrl: 'plug-tamanhog.webp',
    imageAlt: 'plug anal com pedra de metal',
    price: 55,
    category: 'Acessórios',
    tags: ['plug', 'anal', 'metal'],
    rating: 4.4,
    reviewCount: 18,
    highlights: ['Pedra de metal', 'Submissão', 'Estímulo anal'],
  },
];
